### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by salhasalman** [saadhashmi91/Meeshkan-TwitterAuthorhipAttributionChallenge#2]
@saadhashmi91 
I would like to train and test this model in a larger dataset.Do u know any websites or places to get a larger train and test csv s in a format that you have used for the implementation.(with the same headers like author tweet date etc:)
Large dataset in the sense with more number of authors/users.

**Comment by saadhashmi91** [comment]
I don't own the  dataset as it was given to me as part of an onboarding
assessment. However,  a larger dataset can be created using Twitter API.
Thanks
